name: Notion Auto Linker

on:
  schedule:
    - cron: "*/6 * * * *"  # every 6 minutos ---> - cron: "0 */2 * * *" #every 2 hours
  workflow_dispatch:       # allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install requests
        run: pip install requests

      - name: Run Notion Linker
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          DATABASE_A_ID: ${{ secrets.DATABASE_A_ID }}
          DATABASE_B_ID: ${{ secrets.DATABASE_B_ID }}
        run: python main.py
